# docker-compose.yml
version: '3.1'

services:

  dictionary-cli:
    build: ./cli
    environment:
      MICRO_REGISTRY: "mdns"

  dictionary-service:
    build: ./dictionary-service
    ports:
      - 50051:50051
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"
    depends_on: 
      - 'datastore'
    
  datastore:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432