// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dictionary/dictionary.proto

package go_micro_srv_dictionary

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Word struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Word                 string   `protobuf:"bytes,2,opt,name=Word,proto3" json:"Word,omitempty"`
	Definition           string   `protobuf:"bytes,3,opt,name=Definition,proto3" json:"Definition,omitempty"`
	Pronounciation       string   `protobuf:"bytes,4,opt,name=Pronounciation,proto3" json:"Pronounciation,omitempty"`
	Appearances          int32    `protobuf:"varint,5,opt,name=Appearances,proto3" json:"Appearances,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Word) Reset()         { *m = Word{} }
func (m *Word) String() string { return proto.CompactTextString(m) }
func (*Word) ProtoMessage()    {}
func (*Word) Descriptor() ([]byte, []int) {
	return fileDescriptor_dictionary_007405666ff753cd, []int{0}
}
func (m *Word) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Word.Unmarshal(m, b)
}
func (m *Word) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Word.Marshal(b, m, deterministic)
}
func (dst *Word) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Word.Merge(dst, src)
}
func (m *Word) XXX_Size() int {
	return xxx_messageInfo_Word.Size(m)
}
func (m *Word) XXX_DiscardUnknown() {
	xxx_messageInfo_Word.DiscardUnknown(m)
}

var xxx_messageInfo_Word proto.InternalMessageInfo

func (m *Word) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Word) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func (m *Word) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

func (m *Word) GetPronounciation() string {
	if m != nil {
		return m.Pronounciation
	}
	return ""
}

func (m *Word) GetAppearances() int32 {
	if m != nil {
		return m.Appearances
	}
	return 0
}

type GetRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=Query,proto3" json:"Query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dictionary_007405666ff753cd, []int{1}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type Response struct {
	Word                 *Word    `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Words                []*Word  `protobuf:"bytes,2,rep,name=words,proto3" json:"words,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_dictionary_007405666ff753cd, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetWord() *Word {
	if m != nil {
		return m.Word
	}
	return nil
}

func (m *Response) GetWords() []*Word {
	if m != nil {
		return m.Words
	}
	return nil
}

func init() {
	proto.RegisterType((*Word)(nil), "go.micro.srv.dictionary.Word")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.dictionary.GetRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.dictionary.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DictionaryService service

type DictionaryServiceClient interface {
	GetWords(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
	GetWord(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
	Search(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type dictionaryServiceClient struct {
	c           client.Client
	serviceName string
}

func NewDictionaryServiceClient(serviceName string, c client.Client) DictionaryServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.dictionary"
	}
	return &dictionaryServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *dictionaryServiceClient) GetWords(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "DictionaryService.GetWords", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryServiceClient) GetWord(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "DictionaryService.GetWord", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryServiceClient) Search(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "DictionaryService.Search", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DictionaryService service

type DictionaryServiceHandler interface {
	GetWords(context.Context, *GetRequest, *Response) error
	GetWord(context.Context, *GetRequest, *Response) error
	Search(context.Context, *GetRequest, *Response) error
}

func RegisterDictionaryServiceHandler(s server.Server, hdlr DictionaryServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&DictionaryService{hdlr}, opts...))
}

type DictionaryService struct {
	DictionaryServiceHandler
}

func (h *DictionaryService) GetWords(ctx context.Context, in *GetRequest, out *Response) error {
	return h.DictionaryServiceHandler.GetWords(ctx, in, out)
}

func (h *DictionaryService) GetWord(ctx context.Context, in *GetRequest, out *Response) error {
	return h.DictionaryServiceHandler.GetWord(ctx, in, out)
}

func (h *DictionaryService) Search(ctx context.Context, in *GetRequest, out *Response) error {
	return h.DictionaryServiceHandler.Search(ctx, in, out)
}

func init() {
	proto.RegisterFile("dictionary/dictionary.proto", fileDescriptor_dictionary_007405666ff753cd)
}

var fileDescriptor_dictionary_007405666ff753cd = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x6d, 0xb7, 0xce, 0x79, 0x07, 0x03, 0x2f, 0x82, 0x45, 0x51, 0x6a, 0x05, 0xd9, 0x53,
	0xc4, 0xed, 0x17, 0x08, 0x83, 0xb1, 0x37, 0x4d, 0x05, 0x9f, 0x6b, 0x7a, 0xd5, 0x3c, 0x98, 0xd4,
	0xa4, 0x9d, 0xec, 0x6f, 0x88, 0x3f, 0x58, 0x92, 0x4e, 0x3b, 0x84, 0xe2, 0xcb, 0x9e, 0x92, 0x9c,
	0xf3, 0xdd, 0xc3, 0x3d, 0x10, 0x38, 0x2d, 0xa4, 0xa8, 0xa4, 0x56, 0xb9, 0x59, 0x5f, 0xb7, 0x57,
	0x56, 0x1a, 0x5d, 0x69, 0x3c, 0x7e, 0xd1, 0xec, 0x4d, 0x0a, 0xa3, 0x99, 0x35, 0x2b, 0xd6, 0xda,
	0xe9, 0x57, 0x00, 0xfd, 0x47, 0x6d, 0x0a, 0x1c, 0x43, 0xb8, 0x2c, 0xe2, 0x20, 0x09, 0x26, 0x07,
	0x3c, 0x5c, 0x16, 0x88, 0x8d, 0x1e, 0x87, 0x5e, 0x69, 0x98, 0x73, 0x80, 0x39, 0x3d, 0x4b, 0x25,
	0xdd, 0x74, 0xdc, 0xf3, 0xce, 0x96, 0x82, 0x57, 0x30, 0xbe, 0x33, 0x5a, 0xe9, 0x5a, 0x09, 0x99,
	0x7b, 0xa6, 0xef, 0x99, 0x3f, 0x2a, 0x26, 0x30, 0xba, 0x2d, 0x4b, 0xca, 0x4d, 0xae, 0x04, 0xd9,
	0x38, 0x4a, 0x82, 0x49, 0xc4, 0xb7, 0xa5, 0x34, 0x05, 0x58, 0x50, 0xc5, 0xe9, 0xbd, 0x26, 0x5b,
	0xe1, 0x11, 0x44, 0xf7, 0x35, 0x99, 0xf5, 0x66, 0xbd, 0xe6, 0x91, 0x1a, 0x18, 0x72, 0xb2, 0xa5,
	0x56, 0x96, 0xf0, 0x06, 0xfa, 0x1f, 0x6e, 0x5b, 0x07, 0x8c, 0xa6, 0x67, 0xac, 0xa3, 0x2e, 0x73,
	0x35, 0xb8, 0x47, 0x71, 0x06, 0x91, 0x3b, 0x6d, 0x1c, 0x26, 0xbd, 0xff, 0x67, 0x1a, 0x76, 0xfa,
	0x19, 0xc2, 0xe1, 0xfc, 0xd7, 0xca, 0xc8, 0xac, 0xa4, 0x20, 0x7c, 0x80, 0xe1, 0x82, 0x2a, 0xc7,
	0x59, 0xbc, 0xec, 0xcc, 0x69, 0x0b, 0x9d, 0x5c, 0x74, 0x42, 0x3f, 0x8d, 0xd2, 0x3d, 0xcc, 0x60,
	0x7f, 0x93, 0xba, 0xc3, 0x50, 0x0e, 0x83, 0x8c, 0x72, 0x23, 0x5e, 0x77, 0x97, 0xf9, 0x34, 0xf0,
	0x7f, 0x6c, 0xf6, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x48, 0x42, 0x71, 0x6d, 0x82, 0x02, 0x00, 0x00,
}
